###设备滤芯状态信息表
DROP TABLE IF EXISTS `t_device_filter_element`;
CREATE TABLE `t_device_filter_element` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `device_id` varchar(50) NOT NULL DEFAULT '设备id',
  `config_total_flow_filter_count1` double DEFAULT NULL COMMENT '第1个滤芯的配置总流量值（固定）',
  `invalid_date_filter1`  int(11) DEFAULT NULL COMMENT '第1个滤芯的失效时间（固定）',
  `report_hour_filter_count1` int(11) DEFAULT NULL COMMENT '第1个滤芯上报剩余时长',
  `report_flow_filter_count1` double DEFAULT NULL COMMENT '第1个滤芯上报剩余流量',
  `config_total_flow_filter_count2` double DEFAULT NULL COMMENT '第2个滤芯的配置总流量值（固定）',
  `invalid_date_filter2` int(11) DEFAULT NULL COMMENT '第2个滤芯的失效时间（固定）',
  `report_hour_filter_count2` int(11) DEFAULT NULL COMMENT '第2个滤芯上报剩余时长',
  `report_flow_filter_count2` double DEFAULT NULL COMMENT '第2个滤芯上报剩余流量',
  `config_total_flow_filter_count3` double DEFAULT NULL COMMENT '第3个滤芯的配置总流量值（固定）',
  `invalid_date_filter3` int(11) DEFAULT NULL COMMENT '第3个滤芯的失效时间（固定）',
  `report_hour_filter_count3` int(11) DEFAULT NULL COMMENT '第3个滤芯上报剩余时长',
  `report_flow_filter_count3` double DEFAULT NULL COMMENT '第3个滤芯上报剩余流量',
  `config_total_flow_filter_count4` double DEFAULT NULL COMMENT '第4个滤芯的配置总流量值（固定）',
  `invalid_date_filter4` int(11) DEFAULT NULL COMMENT '第4个滤芯的失效时间（固定）',
  `report_hour_filter_count4` int(11) DEFAULT NULL COMMENT '第4个滤芯上报剩余时长',
  `report_flow_filter_count4` double DEFAULT NULL COMMENT '第4个滤芯上报剩余流量',
  `config_total_flow_filter_count5` double DEFAULT NULL COMMENT '第5个滤芯的配置总流量值（固定）',
  `invalid_date_filter5` int(11) DEFAULT NULL COMMENT '第5个滤芯的失效时间（固定）',
  `report_hour_filter_count5` int(11) DEFAULT NULL COMMENT '第5个滤芯上报剩余时长',
  `report_flow_filter_count5` double DEFAULT NULL COMMENT '第5个滤芯上报剩余流量',
  `config_total_flow_filter_count6` double DEFAULT NULL COMMENT '第6个滤芯的配置总流量值（固定）',
  `invalid_date_filter6` int(11) DEFAULT NULL COMMENT '第6个滤芯的失效时间（固定）',
  `report_hour_filter_count6` int(11) DEFAULT NULL COMMENT '第6个滤芯上报剩余时长',
  `report_flow_filter_count6` double DEFAULT NULL COMMENT '第6个滤芯上报剩余流量',
  `config_total_flow_filter_count7` double DEFAULT NULL COMMENT '第7个滤芯的配置总流量值（固定）',
  `invalid_date_filter7` int(11) DEFAULT NULL COMMENT '第7个滤芯的失效时间（固定）',
  `report_hour_filter_count7` int(11) DEFAULT NULL COMMENT '第7个滤芯上报剩余时长',
  `report_flow_filter_count7` double DEFAULT NULL COMMENT '第7个滤芯上报剩余流量',
  `config_total_flow_filter_count8` double DEFAULT NULL COMMENT '第8个滤芯的配置总流量值（固定）',
  `invalid_date_filter8` int(11) DEFAULT NULL COMMENT '第8个滤芯的失效时间（固定）',
  `report_hour_filter_count8` int(11) DEFAULT NULL COMMENT '第8个滤芯上报剩余时长',
  `report_flow_filter_count8` double DEFAULT NULL COMMENT '第8个滤芯上报剩余流量',
  `config_total_flow_filter_count9` double DEFAULT NULL COMMENT '第9个滤芯的配置总流量值（固定）',
  `invalid_date_filter9` int(11) DEFAULT NULL COMMENT '第9个滤芯的失效时间（固定）',
  `report_hour_filter_count9` int(11) DEFAULT NULL COMMENT '第9个滤芯上报剩余时长',
  `report_flow_filter_count9` double DEFAULT NULL COMMENT '第9个滤芯上报剩余流量',
  `config_total_flow_filter_count10` double DEFAULT NULL COMMENT '第10个滤芯的配置总流量值（固定）',
  `invalid_date_filter10` int(11) DEFAULT NULL COMMENT '第10个滤芯的失效时间（固定）',
  `report_hour_filter_count10` int(11) DEFAULT NULL COMMENT '第10个滤芯上报剩余时长',
  `report_flow_filter_count10` double DEFAULT NULL COMMENT '第10个滤芯上报剩余流量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;