server:
  port: 8126
security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1/oauth/check_token
eureka:
  client:
    service-url:
       defaultZone: http://angel:angel@127.0.0.1:8123/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mysql123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    