server:
  port: 8126
security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1/oauth/check_token
eureka:
  client:
    service-url:
       defaultZone: http://angel:angel@127.0.0.1:8123/eureka/
spring:
  datasource:
    username: root
    password: mysql123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://angel:angel123@119.147.77.6:27017/angel_stg?connect=replicaSet&readPreference=secondaryPreferred&safe=true&authMechanism=SCRAM-SHA-1&maxPoolSize=500&minPoolSize=10