server:
  port: 8126

spring:
  application:
    name: angel-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mysql123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://angel:angel@angel-eureka:8123/eureka/      
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  okhttp:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
jasypt:
  encryptor:
    password: angel
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      field-strategy: 1
      id-type: 0
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  mapper-locations: classpath:/dao/*Mapper.xml
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
security:
  oauth2:
    resource:
      loadBalanced: true
      token-info-uri: http://angel-auth/oauth/check_token  