spring:
  application:
    name: angel-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
security:
  oauth2:
    client:
      id: angel_client_id
      client-id: angel
      client-secret: angel
      scope: server
    resource:
      loadBalanced: true
eureka:
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  okhttp:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
jasypt:
  encryptor:
    password: angel
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      field-strategy: default
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  mapper-locations: classpath*:*/*Mapper.xml
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000