server:
  port: 8080
security:
  oauth2:
    resource:
      token-info-uri: http://angel-auth/oauth/check_token
eureka:
  client:
    service-url:
       defaultZone: http://angel:angel@127.0.0.1:8123/eureka/
spring:
  datasource:
    mysql:
      username: root
      password: mysql123
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      initialSize: 5
      minIdle: 5
      maxActive: 20
  data:
    mongodb:
      uri: mongodb://angel:angel123!@#@119.147.77.6:27017/angel?authSource=admin&connect=replicaSet&readPreference=secondaryPreferred&safe=true&authMechanism=SCRAM-SHA-1&maxPoolSize=500&minPoolSize=10