spring:
  security:
    user:
      name: angel
      password: angel
  application:
    name: angel-eureka
  profiles:
    active: dev


# docker-compose部署时候 hostname 换成angel-eureka
# 类似的 redis 使用angel-eureka ,gateway 换成 angel-eureka
eureka:
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9

management:
  endpoints:
    web:
      exposure:
        include: '*'
